name: test

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: blazon-ai/verisynth@v0
        with:
          token: ${{ secrets.TOKEN }}
