name: test

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - uses: honglu2875/test_repo@v1
        with:
          token: ${{ secrets.TOKEN }}
